source 'https://github.com/CocoaPods/Specs.git'

target 'NKJNetworkActivityIndicator_Example', :exclusive => true do
  pod "NKJNetworkActivityIndicator", :path => "../"
end

target 'NKJNetworkActivityIndicator_Tests', :exclusive => true do
  pod "NKJNetworkActivityIndicator", :path => "../"
end
