# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
language: objective-c

before_install:
  - gem install xcpretty

script:
  - pod install --project-directory=Example/
  - make clean test
  - pod lib lint --quick